services:
  accounts:
    image: "jaymistry181027/accounts-service:latest"
    container_name: "accounts-microservice"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - "testNetwork"
  loans:
    image: "jaymistry181027/loans-service:latest"
    container_name: "loans-microservice"
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - "testNetwork"
  cards:
    image: "jaymistry181027/cards-service:latest"
    container_name: "cards-microservice"
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - "testNetwork"
networks:
  testNetwork:
    driver: "bridge"